language: python
python:
  - "3.6"
cache: pip
install:
  - pip install tox-travis coveralls
script:
  - tox
deploy:
  provider: pypi
  skip_cleanup: true
  distributions: "bdist_wheel"
  user:
    secure: "BOLUUuSkc1l6xhoqaRYtAd5vSICVNb7qCHJtEQIRxV9PY/2TCJIlikNLJFfbx00047JwgmQlr41AwmSu1+NkscMI5Sritt0NAQi4HcpceBI7SNfCfuYlNgMuFAQS6MJxSK0J4h8yWmL2EXxBSjzTRmRWtyfPQnrYAwoROoeHWKDZXgRwTY668eGgcNPKawt6E4JhIZMtwAXu+Q6fVlRoQ2u6mF5tiC75r0Hz2o6RgQeXYGOu8o8jlGuF/3d1obSQPw+jJwb0udDg7o3Kr6w/FtmK+k7/S5KjvVr5DcGuEBel9YoROKck5tU+mtvt9h5nDMBDjICL9ExhKSytAbs4LMOD2wRlXTYornfXpIxL24EOrvw8MuF4Koi+AF2RjVfCi7BJsRycBOwtTm7MA/lks8qsi/iRylj2qtSAPHZdpp+FLwnyeV5xIpDHzfuWbPhMyuVqSRZfOnlYR0f7pG4gz2iitnqbfGcBJAgJ/hbq7k1im9Gk1nrdEdawHOFN0b1S+9gr5bFXmNZy5bcSQ7dT101PuHpz1Bis7R5o1WdmY1hzxr2aKISBoKWRPym/3rSNgvRQibEtcN97A1eTWWWCrMO1vc3PJ2DY/Dl7qEGm0VDIxs0pC6SEQqILFc1WfMskaogdxuk7QfFiDPZHOQrAGJdl1zM8QRlK5YYPZu2P9Ik="
  password:
    secure: "ZhSHls5pum2FuzSIgDM3nGor0+Dn9JGNGb8jpVb3e/2HPCbycCjfPUxV7jMls2l5/qaAh2Y/OAcjpZIhwk7MfASCp54TKnGACZuGqJYF557FRaarJ/nLhBJdTMz8fQ7Eaj1wI3tPDW4ac1eVQNfBXCzxjodigQ7TP5Z8gyP/qA5RHwTvIiftSM6/Ly+ERqHMvsgiFPvUYWO0HCDzQuRM7Sw43YQt6KP4D0Jj8SOtshOMGXm3VOnqYW4bcmVvmfd8pU7MEZvIj4ZUeor6lth8m4LBrlRPcbjsVdwm+cpxnFTgL1TYeBisnF4jCnlEkGj4B4VxiQxS9yaQ6ojnSg0NZ9S54UWAR7Y6XPWIspQfKPNVKXwdN8TFEHPNEiMC+O28gurGV8ebLBRruQxkspC0iG4R17kHyfag5CRm26L+l/gQ3aaAaNmYipj77/6b5mD4n+NYIHh4WEg7MInV8cQ8h0sL9I9VOHLSsyfvbeT2/hSg2FlhpBLhqQkW2gkbNuAIUQGYfybP33Jh5/jzSCsCvxPkZXlo/JCLtM3Rs2dBoL7BiYXHbKKBt0B9GG/cg6s1vwscl6kDBdARO2vh7vZ/v4zgkhFbhb0+soQSGSXfJeFmWi7ZhadI7MrEvn7LaU0QYxik7gd133hORi3oClMaCU4Vm7bgDZBljGaAzR8asSI="
  on:
    branch: master
  skip_existing: true
after_success:
- coveralls --verbose